### ISSUE TITLE
Invalid selector if image src attribute contains whitespace

### ISSUE THREAD

**Issue by SalesFeed** [gmmorris/simmerjs#2]
Image src attribute is not validated, e.g. in case of whitespace at the begining the engine will fail.

example html:
```
<img src="		
		someimage.png				
		">
```

**Comment by SalesFeed** [comment]
After debugging it seems like the depth was too small

**Comment by gmmorris** [comment]
Thanks for the issue, I'll look into it.

**Comment by gmmorris** [comment]
Hi,
I have looked into this and I'm afraid this is not a bug, but rather expected behaviour, as the resulting selector would be invalid.
The src attribute should contain a valid URL, and white it can support encoded characters such as regular whitespace, it can't handle new lines.

This is not a Simmer issue, but rather a browser limitation.

One thing to note is that the different browsers render newlines, tabs etc. differently, and so any resulting selector would not be safe for use in different browsers.

**Comment by SalesFeed** [comment]
Hi,
I know it should contain a valid URL, but in many cases websites are not following the standards.
It would be nice if such cases are filtered out. Same goes for invalid classnames and id's.

**Comment by gmmorris** [comment]
Hi,
The problem is that when it is an invalid selector you have no way of knowing if browsers will respect the CSS selector when queried.

The whole point of Simmer is to generate CSS tags which are valid and hence should be respected by browsers. Adding support to this will break many other users, hence I will have to keep this closed.
