### ISSUE TITLE
Simmer stops working after reconfigure

### ISSUE THREAD

**Issue by dawidchyrzynski** [gmmorris/simmerjs#3]
Hi, 
I'm trying to use Simmer library in my JS project (using dist/simmer.js). I need to use configuration different than default one so I've tried to reconfigure Simmer in this way:

```javascript
var simmer = window.Simmer.configure({
 depth: 6
});
var selector = simmer(node);
```

In this case "selector" is always false, no matter what node is. If I remove .configure() call then everything works as expected.

**Comment by gmmorris** [comment]
Hi,
Thanks for the feedback.

Can you provide me with examples to help recreate the issue?
Ideally full DOM of the page where you're having trouble and a selector you're failing to get a result for?
I'll try and have a look in the next day or two.

**Comment by gmmorris** [comment]
Hi,
I took a quick look and realised when the problem was introduced.
I apologise, it's part of the growing pains of updating code from 6 years ago.
I'm in the process of extending all the tests as this code was very poorly tested by myself when originally written many years ago. It's from before I discovered the wonders of TDD. :)

**Comment by dawidchyrzynski** [comment]
Thanks man, I'll take a look at this tomorrow. Hope it works :)

**Comment by gmmorris** [comment]
My pleasure. I hope it works too. ;)

If you're still experiencing a problem I suggest you create a repo with an example where you recreate the issue, it'll help me figure out the problem. :)

**Comment by dawidchyrzynski** [comment]
I checked new version 0.5.5 and it works now. Thank you very much :) I noticed another issue. Is it possible to run simmer on cloned document? In example shown below Simmer() always returns false.

```javascript
var clonedDocument = document.cloneNode(true);

console.log(window.Simmer(document.getElementById("example")); // works
console.log(window.Simmer(clonedDocument.getElementById("example")); // false
```

**Comment by gmmorris** [comment]
hmm interesting usage.
The reason that doesn't work is because the browser injected Simmer automatically binds to the current window.
I think it should work using the context argument, but that's only available via the NPM module, not the browser distribution.

I'm seriously contemplating the API, because currently the library is maintaining an API from 6 years ago which is quite old school in terms of Front End tech. :p

But for now the API is like this:
`js
var clonedDocument = document.cloneNode(true);
import Simmer from 'simmerjs';

const simmer = new Simmer(clonedDocument)
`

This is totally off the top of my head, and I haven't tried it.
I can take a look tomorrow and see how best to support this.

**Comment by dawidchyrzynski** [comment]
Actually "context" argument would be the best solution :) In my project I also use SizzleJS which works based on the same idea and there is no problem with cloned document. It would be nice if Simmer could work in the same way.

**Comment by gmmorris** [comment]
Well the context is there, you can use it, but not using the "drop it" script located at *dist/simmer.js* with the current API, you'll have to use the NPM module instead.

Sizzle and Simmer come from the same "old school" approach. I'm trying to migrate Simmer to a more modern usage using a proper ES Module, rather than an IIF that installs itself.
It's more forwards looking.

**Comment by gmmorris** [comment]
Huh! I'm so short of memory this late at night.

The context *is* available so this should work:

You can do:
```javascript

const clonedDocument = document.cloneNode(true);
const simmerOnClonedDocument = window.Simmer.configure({}, clonedDocument);
```

**Comment by dawidchyrzynski** [comment]
I've tried to use it in this way but it seems that something is broken :)

<img width="1019" alt="zrzut ekranu 2017-06-27 o 10 07 20" src="https://user-images.githubusercontent.com/7567202/27577321-8d8af5ec-5b20-11e7-8849-b168d81ab741.png">

**Comment by gmmorris** [comment]
hmm interesting, this is definitely a use case I wasn't taking into account as it wasn't relevant to our needs at the time.
That said, it should work, so I'll take a look.

If you can provide a repo recreating the problem that might help, but I'll try none the less, I'm assuming it isn't hard to recreate.

**Comment by gmmorris** [comment]
Hi,
I have found the problem.
This should work now, as the context was expecting *a window* not a document, but I've extended it to support document fragments and should work across the board, now.

**Comment by dawidchyrzynski** [comment]
Amazing, it works now. Thank you very much :)
